title: Aditi Krishna # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with 3 years of experience in machine learning, and analytics. Master's degree in Information Systems (Data Science specialization) from Northeastern University, Boston. Previously worked at QuantUniversity, Amazon, Persistent Systems.
  <br><br>
  <a href="https://www.linkedin.com/in/aditikrishna/">View My LinkedIn Profile</a>
  
# remote_theme: pages-themes/minimal@v0.2.0
theme: jekyll-theme-minimal
# plugins:
# - jekyll-remote-theme

google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
