title: Aditi Krishna # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD in CS (Human-AI Interaction, Human-Centered AI, Information Visualization) @ Khoury College - Northeastern University, Boston. Previously worked at QuantUniversity, Amazon, Persistent Systems (4 years of experience in data science, machine learning, and analytics).
  <br><br>
  <a href="https://www.linkedin.com/in/aditikrishna/">View My LinkedIn Profile</a>
  
# remote_theme: pages-themes/minimal@v0.2.0
theme: jekyll-theme-minimal
# plugins:
# - jekyll-remote-theme

google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
